USE COPA
GO


PRINT (' -------------- CARGA DE DADOS DE SELECAO POR GRUPO -------------- ')

INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (1,1)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (2,1)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (3,1)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (4,1)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (5,2)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (6,2)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (7,2)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (8,2)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (9,3)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (10,3)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (11,3)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (12,3)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (13,4)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (14,4)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (15,4)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (16,4)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (17,5)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (18,5)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (19,5)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (20,5)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (21,6)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (22,6)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (23,6)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (24,6)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (25,7)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (26,7)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (27,7)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (28,7)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (29,8)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (30,8)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (31,8)
INSERT INTO copa.TB_SelecaoGrupo (IdSelecao,IdGrupo) VALUES (32,8)