USE COPA
GO



PRINT (' -------------- CARGA DE DADOS DE ARBITRAGEM -------------- ')

INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Al Jassim Abdulrahman','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Alberto Morín','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Alessandro Giallatini','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Alireza Faghani','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Andraz Kovacic','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Andrés Matonte','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Anton Schetinin','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Arsenio Maringule','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Ashley Beecham','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Bruno Boschilia','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Bruno Raphael Pires','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('César Ramos','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Chris Beath','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Ciro Carbone','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Clément Turpin','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Corey Parker','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Cyril Gringore','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Daniele Orsato','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Danilo Ricardo Simon Manis','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('David Jonathan Morán Santos','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Diego Bonfa','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Estádio 974','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Ezequiel Brailosvky','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Facundo Tello','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Fernando Rapallini','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Gabriel Chade','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Hasan al-Mahri','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Héctor Said Martínez Sorto','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Ismail Elfath','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Istvan Kovacs','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Ivan Arcides Barton Cisneros','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Janny Sikazwe','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Jerson Emiliano','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Juan Pablo Belatti','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Kevin Ortega','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Kyle Atkins','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Ma Ning','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Maguette Ndiaye','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Miguel Ángel Hernández','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mohammadreza Abolfazli','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mohammadreza Mansouri','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mohammed Abdulla Hassan','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Nicolas Danos','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Raphael Claus','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Rodrigo Figueiredo Henrique Correa','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Saíd Martínez','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Salima Mukansanga','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Saoud Ahmed Almaqaleh','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Slavko Vincic','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Souru Phatsoane','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Stéphanie Frappart','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Sultan Mohamed Al Hammadi','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Taleb Al Marri','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Tomaz Klancnik','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Victor Gomes','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Wilton Pereira Sampaio','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Yoshimi Yamashita','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Zachari Zeegelaar','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Zakhele Siwela','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mario Escobar','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Caleb Wales','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Juan Mora','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Maguette Ndiaye','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mateu Lahoz','Árbitro ','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Pau Devis','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Roberto Díaz Pérez del Palomar','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mustapha Ghorbal','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mokrane Gourari','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Abdelhak Etchiali','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Jesús Valenzuela','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Jorge Urrego Martínez','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Tulio Moreno','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Daniel Siebert','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Rafael Foltyn','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Jan Seidel','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Szymon Marciniak','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Pawel Sokolnicki','Assistente ','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Tomasz Listkiewicz','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Michael Oliver','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Stuart Burt','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Simon Bennett','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Nicolás Tarán','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Martín Soppi','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Danny Makkelie','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Hessel Steegstra','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Jan de Vries','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Anthony Taylor','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Gary Beswick','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Adam Nunn','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Abdulrahman Al-Jassim','Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Bakary Gassama','Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Elvis Noupue','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mahmoud Ahmed Kamel Abo El Regal','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Matthew Conger', 'Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Mark Rule', 'Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Tevita Makasini', 'Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Salima Mukansanga', 'Quarto Árbitro','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Neuza Ines Back','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Karen Diaz Medina','Assistente','NI');
INSERT INTO copa.TB_Arbitragem (NomArbitro, TpoArbitro, NomPaisOrigem) VALUES ('Kathryn Nesbitt','Assistente','EUA');

UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argélia' WHERE NomArbitro = 'Abdelhak Etchiali';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Catar' WHERE NomArbitro = 'Abdulrahman Al-Jassim';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Inglaterra' WHERE NomArbitro = 'Adam Nunn';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Catar' WHERE NomArbitro = 'Al Jassim Abdulrahman';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'México' WHERE NomArbitro = 'Alberto Morín';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Itália' WHERE NomArbitro = 'Alessandro Giallatini';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Irã' WHERE NomArbitro = 'Alireza Faghani';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Eslovênia' WHERE NomArbitro = 'Andraz Kovacic';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Uruguai' WHERE NomArbitro = 'Andrés Matonte';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Inglaterra' WHERE NomArbitro = 'Anthony Taylor';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Austrália' WHERE NomArbitro = 'Anton Schetinin';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Moçambique' WHERE NomArbitro = 'Arsenio Maringule';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Austrália' WHERE NomArbitro = 'Ashley Beecham';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Gambia' WHERE NomArbitro = 'Bakary Gassama';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'BRASIL' WHERE NomArbitro = 'Bruno Boschilia';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'BRASIL' WHERE NomArbitro = 'Bruno Raphael Pires';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Trinidad E Tobago' WHERE NomArbitro = 'Caleb Wales';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'México' WHERE NomArbitro = 'César Ramos';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Austrália' WHERE NomArbitro = 'Chris Beath';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Itália' WHERE NomArbitro = 'Ciro Carbone';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'França' WHERE NomArbitro = 'Clément Turpin';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Eua' WHERE NomArbitro = 'Corey Parker';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'França' WHERE NomArbitro = 'Cyril Gringore';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Alemanha' WHERE NomArbitro = 'Daniel Siebert';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Itália' WHERE NomArbitro = 'Daniele Orsato';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'BRASIL' WHERE NomArbitro = 'Danilo Ricardo Simon Manis';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Holanda' WHERE NomArbitro = 'Danny Makkelie';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'El Savador' WHERE NomArbitro = 'David Jonathan Morán Santos';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argentina' WHERE NomArbitro = 'Diego Bonfa';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Camarões' WHERE NomArbitro = 'Elvis Noupue';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'NI' WHERE NomArbitro = 'Estádio 974';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argentina' WHERE NomArbitro = 'Ezequiel Brailosvky';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argentina' WHERE NomArbitro = 'Facundo Tello';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argentina' WHERE NomArbitro = 'Fernando Rapallini';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argentina' WHERE NomArbitro = 'Gabriel Chade';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Inglaterra' WHERE NomArbitro = 'Gary Beswick';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Emirados ÁRabes Unidos' WHERE NomArbitro = 'Hasan al-Mahri';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Honduras' WHERE NomArbitro = 'Héctor Said Martínez Sorto';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Holanda' WHERE NomArbitro = 'Hessel Steegstra';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'EUA' WHERE NomArbitro = 'Ismail Elfath';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Romênia' WHERE NomArbitro = 'Istvan Kovacs';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'El Salvador' WHERE NomArbitro = 'Ivan Arcides Barton Cisneros';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Holanda' WHERE NomArbitro = 'Jan de Vries';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Alemanha' WHERE NomArbitro = 'Jan Seidel';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Zambia' WHERE NomArbitro = 'Janny Sikazwe';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Angola' WHERE NomArbitro = 'Jerson Emiliano';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Venezuela' WHERE NomArbitro = 'Jesús Valenzuela';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Venezuela' WHERE NomArbitro = 'Jorge Urrego Martínez';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Costa Rica' WHERE NomArbitro = 'Juan Mora';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argentina' WHERE NomArbitro = 'Juan Pablo Belatti';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'México' WHERE NomArbitro = 'Karen Diaz Medina';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Peru' WHERE NomArbitro = 'Kevin Ortega';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Eua' WHERE NomArbitro = 'Kyle Atkins';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'China' WHERE NomArbitro = 'Ma Ning';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Senegal' WHERE NomArbitro = 'Maguette Ndiaye';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Senegal' WHERE NomArbitro = 'Maguette Ndiaye';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Egito' WHERE NomArbitro = 'Mahmoud Ahmed Kamel Abo El Regal';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Guatemala' WHERE NomArbitro = 'Mario Escobar';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Nova Zelândia' WHERE NomArbitro = 'Mark Rule';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Uruguai' WHERE NomArbitro = 'Martín Soppi';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Espanha' WHERE NomArbitro = 'Mateu Lahoz';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Nova Zelância' WHERE NomArbitro = 'Matthew Conger';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Inglaterra' WHERE NomArbitro = 'Michael Oliver';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'México' WHERE NomArbitro = 'Miguel Ángel Hernández';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Irã' WHERE NomArbitro = 'Mohammadreza Abolfazli';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Irã' WHERE NomArbitro = 'Mohammadreza Mansouri';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Emirados Árabes Unidos' WHERE NomArbitro = 'Mohammed Abdulla Hassan';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argélia' WHERE NomArbitro = 'Mokrane Gourari';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Argélia' WHERE NomArbitro = 'Mustapha Ghorbal';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'BRASIL' WHERE NomArbitro = 'Neuza Ines Back';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'França' WHERE NomArbitro = 'Nicolas Danos';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Uruguai' WHERE NomArbitro = 'Nicolás Tarán';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Espanha' WHERE NomArbitro = 'Pau Devis';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Polônia' WHERE NomArbitro = 'Pawel Sokolnicki';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Alemanha' WHERE NomArbitro = 'Rafael Foltyn';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'BRASIL' WHERE NomArbitro = 'Raphael Claus';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Espanha' WHERE NomArbitro = 'Roberto Díaz Pérez del Palomar';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'BRASIL' WHERE NomArbitro = 'Rodrigo Figueiredo Henrique Correa';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Honduras' WHERE NomArbitro = 'Saíd Martínez';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Ruanda' WHERE NomArbitro = 'Salima Mukansanga';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Ruanda' WHERE NomArbitro = 'Salima Mukansanga';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Catar' WHERE NomArbitro = 'Saoud Ahmed Almaqaleh';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Inglaterra' WHERE NomArbitro = 'Simon Bennett';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Eslovênia' WHERE NomArbitro = 'Slavko Vincic';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Lesoto' WHERE NomArbitro = 'Souru Phatsoane';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'França' WHERE NomArbitro = 'Stéphanie Frappart';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Inglaterra' WHERE NomArbitro = 'Stuart Burt';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Emirados ÁRabes Unidos' WHERE NomArbitro = 'Sultan Mohamed Al Hammadi';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Polônia' WHERE NomArbitro = 'Szymon Marciniak';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Catar' WHERE NomArbitro = 'Taleb Al Marri';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Tonga' WHERE NomArbitro = 'Tevita Makasini';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Polônia' WHERE NomArbitro = 'Tomasz Listkiewicz';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Eslovênia' WHERE NomArbitro = 'Tomaz Klancnik';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Venezuela' WHERE NomArbitro = 'Tulio Moreno';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'África Do Sul' WHERE NomArbitro = 'Victor Gomes';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'BRASIL' WHERE NomArbitro = 'Wilton Pereira Sampaio';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Japão' WHERE NomArbitro = 'Yoshimi Yamashita';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'Suriname' WHERE NomArbitro = 'Zachari Zeegelaar';
UPDATE copa.TB_Arbitragem SET NomPaisOrigem = 'África Do Sul' WHERE NomArbitro = 'Zakhele Siwela';